version: '3.9'
services:
  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: mysql-dev
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/techsupport
      SPRING_DATASOURCE_USERNAME: dev
      SPRING_DATASOURCE_PASSWORD: pass
    depends_on:
      - db

  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: techsupport
      MYSQL_USER: dev
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
